bldr:
    name: singularlab/e2014
    description: E2014 bldr tasks 
    profiles: 
        someTask:
            description: Gets ran when `./bldr.phar build someTask` is called
            tasks:
                - foo
        someOtherTask:
            tasks:
                - bar
        inheritanceExample:
            description: Will run the tasks from `someTask` and then `someOtherTask`.
            uses:
                before: [someTask]
                after: [someOtherTask]
    tasks:
        foo:
            description: Foo task
            calls:
                -
                    type: exec
                    executable: echo
                    arguments: [Hello World]
        bar:
            description: Bar task
            calls:
                -
                    type: exec
                    executable: sleep
                    arguments: [1]
