fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }

    indexes:
        e2014:
            settings:
                analysis:
                    analyzer:
                        comma:
                            type: pattern
                            pattern: ","
            types:
                candidato:
                    mappings:
                        org_pol: ~
                        cargo_autoridad: { analyzer : comma }
                        postula_ubigeo: ~
                        postula_ubigeo_dep:
                            analyzer : comma
                            boost: 10
                        postula_ubigeo_pro:
                            analyzer : comma
                            boost: 10
                        postula_ubigeo_dis:
                            analyzer : comma
                            boost: 10
                        forma_designacion: ~
                        dni: ~
                        appaterno:
                            boost: 5
                        apmaterno:
                            boost: 5
                        nombres:
                            boost: 5
                        fdn: ~
                        sexo: ~
                        email: ~
                        nac_pais: ~
                        nac_ubigeo: ~
                        nac_ubigeo_dep: ~
                        nac_ubigeo_pro: ~
                        nac_ubigeo_dis: ~
                        residencia: ~
                        residencia_ubigeo: ~
                        residencia_ubigeo_dep: ~
                        residencia_ubigeo_pro: ~
                        residencia_ubigeo_dis: ~
                        residencia_tiempo: ~
                    persistence:
                        driver: orm
                        model: Hackspace\E2014Bundle\Entity\Candidato
                        provider: ~
                        listener: ~
                        finder: ~