fos_elastica:
    clients:
        default: { host: 127.0.0.1, port: 9200 }

    indexes:
        e2014:
            settings:
                analysis:
                    analyzer:
                        comma:
                            type: pattern
                            pattern: ","
            types:
                candidato:
                    mappings:
                        org_pol: ~
                        cargo_autoridad: { analyzer : comma }
                        postula_ubigeo: ~
                        postula_ubigeo_cod_dep: ~
                        postula_ubigeo_cod_pro: ~
                        postula_ubigeo_cod_dis: ~
                        postula_ubigeo_dep: ~
                            #analyzer : comma
                        postula_ubigeo_pro: ~
                            #analyzer : comma
                        postula_ubigeo_dis: ~
                            #analyzer : comma
                        forma_designacion: ~
                        dni: ~
                        appaterno:
                            boost: 5
                        apmaterno:
                            boost: 5
                        nombres:
                            boost: 5
                        fdn: ~
                        sexo: ~
                        email: ~
                        nac_pais: ~
                        nac_ubigeo: ~
                        #nac_ubigeo_dep: ~
                        #nac_ubigeo_pro: ~
                        #nac_ubigeo_dis: ~
                        residencia: ~
                        residencia_ubigeo: ~
                        #residencia_ubigeo_dep: ~
                        #residencia_ubigeo_pro: ~
                        #residencia_ubigeo_dis: ~
                        residencia_tiempo: ~
                        postula_ubigeo_e:
                          type: "nested"
                          properties:
                            ubigeo: ~
                            ubigeo_dep: ~
                            ubigeo_pro: ~
                            ubigeo_dis: ~
                        educacion_superior:
                          type: "object"
                          properties:
                            candidato_jne_id: ~
                            fe_mod: ~
                            id_educacion: ~
                            mes_inicio: ~
                            pais: ~
                            fg_no_universitario: ~
                            fg_estudio_realizado: ~
                            nombre_estudio: ~
                            lugar_estudio: ~
                            fg_estado: ~
                            fg_hasta_actualidad: ~
                            ano_inicio: ~
                            tipo_documento: ~
                            tipo_postgrado: ~
                            mes_final: ~
                            cod_anr: ~
                            eli: ~
                            nombre_centro: ~
                            cre: ~
                            tipo_grado: ~
                            fg_extrangero: ~
                            otro_tipo_documento: ~
                            nombre_carrera: ~
                            otro_tipo_grado: ~
                            tipo_estudio: ~
                            fg_concluido: ~
                            ano_final: ~
                            ubigeo: ~
                    persistence:
                        driver: orm
                        model: Hackspace\E2014Bundle\Entity\Candidato
                        provider:
                          query_builder_method: elasticaPopulateQueryBuilder
                        listener: ~
                        finder: ~