parameters:
#    hackspace_e2014.example.class: Hackspace\E2014Bundle\Example

services:
#    hackspace_e2014.example:
#        class: %hackspace_e2014.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
