parameters:
#    hackspace_e2014.example.class: Hackspace\E2014Bundle\Example
    hackspace_e2014.q_form_handler.class: Hackspace\E2014Bundle\Business\QFormHandler
    hackspace_e2014.c_searcher.class: Hackspace\E2014Bundle\Business\CSearcher
    hackspace_e2014.c_facet_factory.class: Hackspace\E2014Bundle\Business\CFacetFactory

services:
#    hackspace_e2014.example:
#        class: %hackspace_e2014.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    hackspace_e2014.candidato_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Hackspace\E2014Bundle\Entity\Candidato

    hackspace_e2014.ubigeo_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Hackspace\E2014Bundle\Entity\Ubigeo

    hackspace_e2014.q_form_handler:
        class: %hackspace_e2014.q_form_handler.class%
        arguments: [@form.factory]

    hackspace_e2014.c_searcher:
        class: %hackspace_e2014.c_searcher.class%
        arguments: [@fos_elastica.finder.e2014.candidato, @hackspace_e2014.c_facet_factory ]

    hackspace_e2014.c_facet_factory:
        class: %hackspace_e2014.c_facet_factory.class%
        arguments: []
