parameters:
#    hackspace_e2014.example.class: Hackspace\E2014Bundle\Example
    hackspace_e2014.q_form_handler.class: Hackspace\E2014Bundle\Business\QFormHandler
    hackspace_e2014.c_searcher.class: Hackspace\E2014Bundle\Business\CSearcher

services:
#    hackspace_e2014.example:
#        class: %hackspace_e2014.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

      hackspace_e2014.q_form_handler:
        class: %hackspace_e2014.q_form_handler.class%
        arguments: [@form.factory]

      hackspace_e2014.c_searcher:
        class: %hackspace_e2014.c_searcher.class%
        arguments: [@fos_elastica.finder.e2014.candidato]
