<?php

namespace Hackspace\E2014Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatoRepository extends EntityRepository
{
}
